name: Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull image from Docker Hub
        run: docker pull mariadb:latest

      - name: Tag image for Harbor
        run: docker tag mariadb:latest harbor.serengeti.app/oasis/my-image:latest

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.serengeti.app
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Push image to Harbor
        run: docker push harbor.serengeti.app/oasis/my-image:latest
