name: Push Docker Image to Harbor

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: serengeti-max
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull image from Docker Hub
        run: docker pull mariadb:latest

      # 이미지 태깅 추가
      - name: Set Image Registry and Name Based on Branch  
        run: |
          echo "MARIADB_IMAGE=harbor.serengeti.app/administrator2/67a0b760-bf98-4c87-8869-16797db74cf2" >> $GITHUB_ENV  
          echo "HARBOR_DOMAIN=harbor.serengeti.app" >> $GITHUB_ENV  
      - name: Tag image for Harbor
        run: docker tag mariadb:latest ${{ env.MARIADB_IMAGE }}:latest
        
      
      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ env.HARBOR_DOMAIN }}
          username: administrator2
          password: h3ctgknem1qZ@

      - name: Push image to Harbor
        run: docker push  ${{ env.MARIADB_IMAGE }}:latest
