name: Push Docker Image to Harbor

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: serengeti-max
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull image from Docker Hub
        run: docker pull mariadb:latest

      - name: Tag image for Harbor
        run: docker tag mariadb:latest harbor.serengeti.app/oasis/my-image:latest

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.serengeti.app
          username: admin
          password: Savana12345

      - name: Push image to Harbor
        run: docker push harbor.serengeti.app/oasis/my-image:latest
